# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Documents\eclipse-oxygen-workspace\Clue-Less\ClueLess.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ClueLess(object):
    def setupUi(self, ClueLess):
        ClueLess.setObjectName("ClueLess")
        ClueLess.resize(797, 601)
        self.stackedWidget = QtWidgets.QStackedWidget(ClueLess)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 801, 601))
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setObjectName("stackedWidget")

        '''MAIN MENU - Stacked Widget 0''' 
        self.mainMenu = QtWidgets.QWidget()
        self.mainMenu.setObjectName("mainMenu")
        self.instructionsButton = QtWidgets.QPushButton(self.mainMenu)
        self.instructionsButton.setGeometry(QtCore.QRect(180, 250, 461, 71))
        self.instructionsButton.setObjectName("instructionsButton")
        self.gameLobbyButton = QtWidgets.QPushButton(self.mainMenu)
        self.gameLobbyButton.setEnabled(True)
        self.gameLobbyButton.setGeometry(QtCore.QRect(181, 162, 461, 71))
        self.gameLobbyButton.setMouseTracking(False)
        self.gameLobbyButton.setObjectName("gameLobbyButton")
        self.creditsButton = QtWidgets.QPushButton(self.mainMenu)
        self.creditsButton.setGeometry(QtCore.QRect(180, 430, 461, 71))
        self.creditsButton.setObjectName("creditsButton")
        self.mainOptionsButton = QtWidgets.QPushButton(self.mainMenu)
        self.mainOptionsButton.setGeometry(QtCore.QRect(180, 340, 461, 71))
        self.mainOptionsButton.setObjectName("mainOptionsButton")
        self.stackedWidget.addWidget(self.mainMenu)

        '''GAME LOBBY MENU - Stacked Widget 1'''
        self.gameLobbyMenu = QtWidgets.QWidget()
        self.gameLobbyMenu.setObjectName("gameLobbyMenu")
        self.joinGameButton = QtWidgets.QPushButton(self.gameLobbyMenu)
        self.joinGameButton.setGeometry(QtCore.QRect(180, 300, 461, 71))
        self.joinGameButton.setObjectName("joinGameButton")
        self.gameLobbyBack = QtWidgets.QPushButton(self.gameLobbyMenu)
        self.gameLobbyBack.setGeometry(QtCore.QRect(180, 390, 461, 71))
        self.gameLobbyBack.setObjectName("gameLobbyBack")
        self.createGameButton = QtWidgets.QPushButton(self.gameLobbyMenu)
        self.createGameButton.setGeometry(QtCore.QRect(180, 210, 461, 71))
        self.createGameButton.setObjectName("createGameButton")
        self.GameLobbyLabel = QtWidgets.QLabel(self.gameLobbyMenu)
        self.GameLobbyLabel.setGeometry(QtCore.QRect(230, 100, 361, 71))
        self.GameLobbyLabel.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.GameLobbyLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.GameLobbyLabel.setObjectName("GameLobbyLabel")
        self.stackedWidget.addWidget(self.gameLobbyMenu)

        '''CREATE GAME MENU - Stacked Widget 2'''
        self.createGameMenu = QtWidgets.QWidget()
        self.createGameMenu.setObjectName("createGameMenu")
        self.createGameLabel = QtWidgets.QLabel(self.createGameMenu)
        self.createGameLabel.setGeometry(QtCore.QRect(240, 110, 361, 71))
        self.createGameLabel.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.createGameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.createGameLabel.setObjectName("createGameLabel")
        self.hostIpAddressBox = QtWidgets.QGroupBox(self.createGameMenu)
        self.hostIpAddressBox.setGeometry(QtCore.QRect(230, 210, 371, 91))
        self.hostIpAddressBox.setObjectName("hostIpAddressBox")
        self.ipNotificationLabel = QtWidgets.QLabel(self.hostIpAddressBox)
        self.ipNotificationLabel.setGeometry(QtCore.QRect(20, 20, 331, 16))
        self.ipNotificationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ipNotificationLabel.setObjectName("ipNotificationLabel")
        self.ipAddressLabel = QtWidgets.QLabel(self.hostIpAddressBox)
        self.ipAddressLabel.setGeometry(QtCore.QRect(14, 50, 341, 20))
        self.ipAddressLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ipAddressLabel.setObjectName("ipAddressLabel")
        self.createButton = QtWidgets.QPushButton(self.createGameMenu)
        self.createButton.setGeometry(QtCore.QRect(230, 430, 161, 51))
        self.createButton.setObjectName("createButton")
        self.cancelButton = QtWidgets.QPushButton(self.createGameMenu)
        self.cancelButton.setGeometry(QtCore.QRect(440, 430, 161, 51))
        self.cancelButton.setObjectName("cancelButton")
        self.playerNameLabel = QtWidgets.QLabel(self.createGameMenu)
        self.playerNameLabel.setGeometry(QtCore.QRect(200, 330, 131, 41))
        self.playerNameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.playerNameLabel.setObjectName("playerNameLabel")
        self.gameHostName = QtWidgets.QLineEdit(self.createGameMenu)
        self.gameHostName.setGeometry(QtCore.QRect(350, 340, 181, 22))
        self.gameHostName.setObjectName("gameHostName")
        self.stackedWidget.addWidget(self.createGameMenu)
        
        '''JOIN GAME MENU - Stacked Widget 3'''
        self.joinGameMenu = QtWidgets.QWidget()
        self.joinGameMenu.setObjectName("joinGameMenu")
        self.newPlayerName = QtWidgets.QLineEdit(self.joinGameMenu)
        self.newPlayerName.setGeometry(QtCore.QRect(350, 330, 181, 22))
        self.newPlayerName.setObjectName("newPlayerName")
        self.joinGameButton_3 = QtWidgets.QPushButton(self.joinGameMenu)
        self.joinGameButton_3.setGeometry(QtCore.QRect(230, 420, 161, 51))
        self.joinGameButton_3.setObjectName("joinGameButton_3")
        self.playerNameLabel_3 = QtWidgets.QLabel(self.joinGameMenu)
        self.playerNameLabel_3.setGeometry(QtCore.QRect(200, 320, 131, 41))
        self.playerNameLabel_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.playerNameLabel_3.setObjectName("playerNameLabel_3")
        self.hostIpAddressBox_3 = QtWidgets.QGroupBox(self.joinGameMenu)
        self.hostIpAddressBox_3.setGeometry(QtCore.QRect(230, 200, 371, 91))
        self.hostIpAddressBox_3.setObjectName("hostIpAddressBox_3")
        self.gameIPInstruction = QtWidgets.QLabel(self.hostIpAddressBox_3)
        self.gameIPInstruction.setGeometry(QtCore.QRect(20, 20, 331, 16))
        self.gameIPInstruction.setAlignment(QtCore.Qt.AlignCenter)
        self.gameIPInstruction.setObjectName("gameIPInstruction")
        self.gameIPInput = QtWidgets.QLineEdit(self.hostIpAddressBox_3)
        self.gameIPInput.setGeometry(QtCore.QRect(20, 50, 331, 22))
        self.gameIPInput.setAlignment(QtCore.Qt.AlignCenter)
        self.gameIPInput.setObjectName("gameIPInput")
        self.cancelJoinButton = QtWidgets.QPushButton(self.joinGameMenu)
        self.cancelJoinButton.setGeometry(QtCore.QRect(440, 420, 161, 51))
        self.cancelJoinButton.setObjectName("cancelJoinButton")
        self.joinGameLabel = QtWidgets.QLabel(self.joinGameMenu)
        self.joinGameLabel.setGeometry(QtCore.QRect(240, 100, 361, 71))
        self.joinGameLabel.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.joinGameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.joinGameLabel.setObjectName("joinGameLabel")
        self.stackedWidget.addWidget(self.joinGameMenu)


        '''MAIN OPTIONS MENU - Stacked Widget 4'''
        self.mainOptionsMenu = QtWidgets.QWidget()
        self.mainOptionsMenu.setObjectName("mainOptionsMenu")
        self.mainOptionsBack = QtWidgets.QPushButton(self.mainOptionsMenu)
        self.mainOptionsBack.setGeometry(QtCore.QRect(180, 390, 461, 71))
        self.mainOptionsBack.setObjectName("mainOptionsBack")
        self.OptionsLabel = QtWidgets.QLabel(self.mainOptionsMenu)
        self.OptionsLabel.setGeometry(QtCore.QRect(230, 70, 361, 71))
        self.OptionsLabel.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.OptionsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.OptionsLabel.setObjectName("OptionsLabel")
        self.mainMusicBox = QtWidgets.QGroupBox(self.mainOptionsMenu)
        self.mainMusicBox.setGeometry(QtCore.QRect(180, 170, 461, 91))
        self.mainMusicBox.setObjectName("mainMusicBox")
        self.mainMusicSlider = QtWidgets.QSlider(self.mainMusicBox)
        self.mainMusicSlider.setGeometry(QtCore.QRect(10, 40, 431, 22))
        self.mainMusicSlider.setProperty("value", 99)
        self.mainMusicSlider.setOrientation(QtCore.Qt.Horizontal)
        self.mainMusicSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.mainMusicSlider.setTickInterval(10)
        self.mainMusicSlider.setObjectName("mainMusicSlider")
        self.mainEffectsBox = QtWidgets.QGroupBox(self.mainOptionsMenu)
        self.mainEffectsBox.setGeometry(QtCore.QRect(180, 280, 461, 91))
        self.mainEffectsBox.setObjectName("mainEffectsBox")
        self.mainEffectsSlider = QtWidgets.QSlider(self.mainEffectsBox)
        self.mainEffectsSlider.setGeometry(QtCore.QRect(10, 40, 431, 22))
        self.mainEffectsSlider.setOrientation(QtCore.Qt.Horizontal)
        self.mainEffectsSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.mainEffectsSlider.setTickInterval(10)
        self.mainEffectsSlider.setObjectName("mainEffectsSlider")
        self.stackedWidget.addWidget(self.mainOptionsMenu)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)

        self.retranslateUi(ClueLess)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ClueLess)

    def retranslateUi(self, ClueLess):
        _translate = QtCore.QCoreApplication.translate
        ClueLess.setWindowTitle(_translate("ClueLess", "Clue-Less"))
        self.instructionsButton.setText(_translate("ClueLess", "How to Play"))
        self.gameLobbyButton.setText(_translate("ClueLess", "Game Lobby"))
        self.creditsButton.setText(_translate("ClueLess", "Credits"))
        self.mainOptionsButton.setText(_translate("ClueLess", "Options"))
        self.joinGameButton.setText(_translate("ClueLess", "Join Game"))
        self.gameLobbyBack.setText(_translate("ClueLess", "Back"))
        self.createGameButton.setText(_translate("ClueLess", "Create Game"))
        self.GameLobbyLabel.setText(_translate("ClueLess", "Game Lobby"))
        self.createGameLabel.setText(_translate("ClueLess", "Create Game"))
        self.hostIpAddressBox.setTitle(_translate("ClueLess", "Host IP Address"))
        self.ipNotificationLabel.setText(_translate("ClueLess", "Other players will need this IP address to join."))
        self.ipAddressLabel.setText(_translate("ClueLess", "TextLabel"))
        self.createButton.setText(_translate("ClueLess", "Create"))
        self.cancelButton.setText(_translate("ClueLess", "Cancel"))
        self.playerNameLabel.setText(_translate("ClueLess", "Player Name:"))
        
        self.joinGameButton_3.setText(_translate("ClueLess", "Join"))
        self.playerNameLabel_3.setText(_translate("ClueLess", "Player Name:"))
        self.hostIpAddressBox_3.setTitle(_translate("ClueLess", "Host IP Address"))
        self.gameIPInstruction.setText(_translate("ClueLess", "Enter the IP address of the game you want to join."))
        self.cancelJoinButton.setText(_translate("ClueLess", "Cancel"))
        self.joinGameLabel.setText(_translate("ClueLess", "Join Game"))
        
        self.mainOptionsBack.setText(_translate("ClueLess", "Back"))
        self.OptionsLabel.setText(_translate("ClueLess", "Options"))
        self.mainMusicBox.setTitle(_translate("ClueLess", "Music"))
        self.mainEffectsBox.setTitle(_translate("ClueLess", "Sound Effects"))
        

