# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Documents\eclipse-oxygen-workspace\Clue-Less\GameBoard.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GameBoard(object):
    def setupUi(self, GameBoard):
        GameBoard.setObjectName("GameBoard")
        GameBoard.resize(797, 601)
        self.stackedWidget = QtWidgets.QStackedWidget(GameBoard)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 801, 601))
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setObjectName("stackedWidget")

        '''GAME LOBBY'''
        self.gameLobby = QtWidgets.QWidget()
        self.gameLobby.setObjectName("gameLobby")
        self.playerOneLabel = QtWidgets.QLabel(self.gameLobby)
        self.playerOneLabel.setGeometry(QtCore.QRect(120, 40, 161, 51))
        self.playerOneLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.playerOneLabel.setObjectName("playerOneLabel")
        self.playerTwoLabel = QtWidgets.QLabel(self.gameLobby)
        self.playerTwoLabel.setGeometry(QtCore.QRect(120, 110, 161, 51))
        self.playerTwoLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.playerTwoLabel.setObjectName("playerTwoLabel")
        self.playerThreeLabel = QtWidgets.QLabel(self.gameLobby)
        self.playerThreeLabel.setGeometry(QtCore.QRect(120, 180, 161, 51))
        self.playerThreeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.playerThreeLabel.setObjectName("playerThreeLabel")
        self.playerFourLabel = QtWidgets.QLabel(self.gameLobby)
        self.playerFourLabel.setGeometry(QtCore.QRect(120, 250, 161, 51))
        self.playerFourLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.playerFourLabel.setObjectName("playerFourLabel")
        self.playerFiveLabel = QtWidgets.QLabel(self.gameLobby)
        self.playerFiveLabel.setGeometry(QtCore.QRect(120, 330, 161, 51))
        self.playerFiveLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.playerFiveLabel.setObjectName("playerFiveLabel")
        self.playerSixLabel = QtWidgets.QLabel(self.gameLobby)
        self.playerSixLabel.setGeometry(QtCore.QRect(120, 400, 161, 51))
        self.playerSixLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.playerSixLabel.setObjectName("playerSixLabel")
        self.playerOneNameSlot = QtWidgets.QLineEdit(self.gameLobby)
        self.playerOneNameSlot.setEnabled(True)
        self.playerOneNameSlot.setGeometry(QtCore.QRect(290, 50, 281, 31))
        self.playerOneNameSlot.setReadOnly(True)
        self.playerOneNameSlot.setObjectName("playerOneNameSlot")
        self.playerTwoNameSlot = QtWidgets.QLineEdit(self.gameLobby)
        self.playerTwoNameSlot.setGeometry(QtCore.QRect(290, 120, 281, 31))
        self.playerTwoNameSlot.setReadOnly(True)
        self.playerTwoNameSlot.setObjectName("playerTwoNameSlot")
        self.playerThreeNameSlot = QtWidgets.QLineEdit(self.gameLobby)
        self.playerThreeNameSlot.setGeometry(QtCore.QRect(290, 190, 281, 31))
        self.playerThreeNameSlot.setReadOnly(True)
        self.playerThreeNameSlot.setObjectName("playerThreeNameSlot")
        self.playerFourNameSlot = QtWidgets.QLineEdit(self.gameLobby)
        self.playerFourNameSlot.setGeometry(QtCore.QRect(290, 260, 281, 31))
        self.playerFourNameSlot.setReadOnly(True)
        self.playerFourNameSlot.setObjectName("playerFourNameSlot")
        self.playerFiveNameSlot = QtWidgets.QLineEdit(self.gameLobby)
        self.playerFiveNameSlot.setGeometry(QtCore.QRect(290, 340, 281, 31))
        self.playerFiveNameSlot.setReadOnly(True)
        self.playerFiveNameSlot.setObjectName("playerFiveNameSlot")
        self.playerSixNameSlot = QtWidgets.QLineEdit(self.gameLobby)
        self.playerSixNameSlot.setGeometry(QtCore.QRect(290, 410, 281, 31))
        self.playerSixNameSlot.setReadOnly(True)
        self.playerSixNameSlot.setObjectName("playerSixNameSlot")
        self.startGameButton = QtWidgets.QPushButton(self.gameLobby)
        self.startGameButton.setGeometry(QtCore.QRect(232, 480, 151, 51))
        self.startGameButton.setObjectName("startGameButton")
        self.cancelStartButton = QtWidgets.QPushButton(self.gameLobby)
        self.cancelStartButton.setGeometry(QtCore.QRect(410, 480, 161, 51))
        self.cancelStartButton.setObjectName("cancelStartButton")
        self.stackedWidget.addWidget(self.gameLobby)

        '''CHARACTER SELECTION'''
        self.characterSelection = QtWidgets.QWidget()
        self.characterSelection.setObjectName("characterSelection")
        self.characterSelectionLabel = QtWidgets.QLabel(self.characterSelection)
        self.characterSelectionLabel.setGeometry(QtCore.QRect(210, 40, 361, 71))
        self.characterSelectionLabel.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.characterSelectionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.characterSelectionLabel.setObjectName("characterSelectionLabel")
        self.continueButton = QtWidgets.QPushButton(self.characterSelection)
        self.continueButton.setGeometry(QtCore.QRect(310, 480, 161, 51))
        self.continueButton.setObjectName("continueButton")
        self.continueButton.setEnabled(False)
        self.scarlett = QtWidgets.QPushButton(self.characterSelection)
        self.scarlett.setEnabled(True)
        self.scarlett.setGeometry(QtCore.QRect(160, 120, 111, 141))
        self.scarlett.setAutoFillBackground(False)
        self.scarlett.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("scarlett.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.scarlett.setIcon(icon)
        self.scarlett.setIconSize(QtCore.QSize(125, 125))
        self.scarlett.setCheckable(True)
        self.scarlett.setAutoExclusive(True)
        self.scarlett.setObjectName("scarlett")
        self.mustard = QtWidgets.QPushButton(self.characterSelection)
        self.mustard.setGeometry(QtCore.QRect(340, 120, 111, 141))
        self.mustard.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("mustard.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mustard.setIcon(icon1)
        self.mustard.setIconSize(QtCore.QSize(125, 125))
        self.mustard.setCheckable(True)
        self.mustard.setAutoExclusive(True)
        self.mustard.setObjectName("mustard")
        self.white = QtWidgets.QPushButton(self.characterSelection)
        self.white.setGeometry(QtCore.QRect(510, 120, 111, 141))
        self.white.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("white.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.white.setIcon(icon2)
        self.white.setIconSize(QtCore.QSize(125, 125))
        self.white.setCheckable(True)
        self.white.setAutoExclusive(True)
        self.white.setObjectName("white")
        self.green = QtWidgets.QPushButton(self.characterSelection)
        self.green.setGeometry(QtCore.QRect(160, 300, 111, 141))
        self.green.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("green.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.green.setIcon(icon3)
        self.green.setIconSize(QtCore.QSize(125, 125))
        self.green.setCheckable(True)
        self.green.setAutoExclusive(True)
        self.green.setObjectName("green")
        self.peacock = QtWidgets.QPushButton(self.characterSelection)
        self.peacock.setGeometry(QtCore.QRect(340, 300, 111, 141))
        self.peacock.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("peacock.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.peacock.setIcon(icon4)
        self.peacock.setIconSize(QtCore.QSize(125, 125))
        self.peacock.setCheckable(True)
        self.peacock.setAutoExclusive(True)
        self.peacock.setObjectName("peacock")
        self.plum = QtWidgets.QPushButton(self.characterSelection)
        self.plum.setGeometry(QtCore.QRect(510, 300, 111, 141))
        self.plum.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("plum.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.plum.setIcon(icon5)
        self.plum.setIconSize(QtCore.QSize(125, 125))
        self.plum.setCheckable(True)
        self.plum.setAutoExclusive(True)
        self.plum.setObjectName("plum")
        self.stackedWidget.addWidget(self.characterSelection)
	

        '''GAME BOARD'''
        self.gameBoard = QtWidgets.QWidget()
        self.gameBoard.setObjectName("gameBoard")
        # Tool Box
        self.toolBox = QtWidgets.QToolBox(self.gameBoard)
        self.toolBox.setGeometry(QtCore.QRect(594, 160, 201, 291))
        self.toolBox.setObjectName("toolBox")
        self.suspectTracker = QtWidgets.QWidget()
        self.suspectTracker.setGeometry(QtCore.QRect(0, 0, 201, 198))
        self.suspectTracker.setObjectName("suspectTracker")
        self.msTrackerLabel = QtWidgets.QLabel(self.suspectTracker)
        self.msTrackerLabel.setGeometry(QtCore.QRect(0, 20, 101, 16))
        self.msTrackerLabel.setObjectName("msTrackerLabel")
        self.cmTrackerLabel = QtWidgets.QLabel(self.suspectTracker)
        self.cmTrackerLabel.setGeometry(QtCore.QRect(0, 40, 101, 16))
        self.cmTrackerLabel.setObjectName("cmTrackerLabel")
        self.mwTrackerLabel = QtWidgets.QLabel(self.suspectTracker)
        self.mwTrackerLabel.setGeometry(QtCore.QRect(0, 60, 101, 16))
        self.mwTrackerLabel.setObjectName("mwTrackerLabel")
        self.mgTrackerLabel = QtWidgets.QLabel(self.suspectTracker)
        self.mgTrackerLabel.setGeometry(QtCore.QRect(0, 80, 101, 16))
        self.mgTrackerLabel.setObjectName("mgTrackerLabel")
        self.mpTrackerLabel = QtWidgets.QLabel(self.suspectTracker)
        self.mpTrackerLabel.setGeometry(QtCore.QRect(0, 100, 101, 16))
        self.mpTrackerLabel.setObjectName("mpTrackerLabel")
        self.ppTrackerLabel = QtWidgets.QLabel(self.suspectTracker)
        self.ppTrackerLabel.setGeometry(QtCore.QRect(0, 120, 101, 16))
        self.ppTrackerLabel.setObjectName("ppTrackerLabel")
        self.msYButton = QtWidgets.QRadioButton(self.suspectTracker)
        self.msYButton.setGeometry(QtCore.QRect(110, 20, 21, 20))
        self.msYButton.setText("")
        self.msYButton.setObjectName("msYButton")
        self.buttonGroup = QtWidgets.QButtonGroup(GameBoard)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.msYButton)
        self.msNButton = QtWidgets.QRadioButton(self.suspectTracker)
        self.msNButton.setGeometry(QtCore.QRect(140, 20, 21, 20))
        self.msNButton.setText("")
        self.msNButton.setObjectName("msNButton")
        self.buttonGroup.addButton(self.msNButton)
        self.msUButton = QtWidgets.QRadioButton(self.suspectTracker)
        self.msUButton.setGeometry(QtCore.QRect(170, 20, 21, 20))
        self.msUButton.setText("")
        self.msUButton.setObjectName("msUButton")
        self.buttonGroup.addButton(self.msUButton)
        self.cmUButton = QtWidgets.QRadioButton(self.suspectTracker)
        self.cmUButton.setGeometry(QtCore.QRect(170, 40, 21, 20))
        self.cmUButton.setText("")
        self.cmUButton.setObjectName("cmUButton")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(GameBoard)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.cmUButton)
        self.cmNButton = QtWidgets.QRadioButton(self.suspectTracker)
        self.cmNButton.setGeometry(QtCore.QRect(140, 40, 21, 20))
        self.cmNButton.setText("")
        self.cmNButton.setObjectName("cmNButton")
        self.buttonGroup_2.addButton(self.cmNButton)
        self.cmYButton = QtWidgets.QRadioButton(self.suspectTracker)
        self.cmYButton.setGeometry(QtCore.QRect(110, 40, 21, 20))
        self.cmYButton.setText("")
        self.cmYButton.setObjectName("cmYButton")
        self.buttonGroup_2.addButton(self.cmYButton)
        self.mwUButton = QtWidgets.QRadioButton(self.suspectTracker)
        self.mwUButton.setGeometry(QtCore.QRect(170, 60, 21, 20))
        self.mwUButton.setText("")
        self.mwUButton.setObjectName("mwUButton")
        self.buttonGroup_3 = QtWidgets.QButtonGroup(GameBoard)
        self.buttonGroup_3.setObjectName("buttonGroup_3")
        self.buttonGroup_3.addButton(self.mwUButton)
        self.mwNButton = QtWidgets.QRadioButton(self.suspectTracker)
        self.mwNButton.setGeometry(QtCore.QRect(140, 60, 21, 20))
        self.mwNButton.setText("")
        self.mwNButton.setObjectName("mwNButton")
        self.buttonGroup_3.addButton(self.mwNButton)
        self.mwYButton = QtWidgets.QRadioButton(self.suspectTracker)
        self.mwYButton.setGeometry(QtCore.QRect(110, 60, 21, 20))
        self.mwYButton.setText("")
        self.mwYButton.setObjectName("mwYButton")
        self.buttonGroup_3.addButton(self.mwYButton)
        self.mgUButton = QtWidgets.QRadioButton(self.suspectTracker)
        self.mgUButton.setGeometry(QtCore.QRect(170, 80, 21, 20))
        self.mgUButton.setText("")
        self.mgUButton.setObjectName("mgUButton")
        self.buttonGroup_4 = QtWidgets.QButtonGroup(GameBoard)
        self.buttonGroup_4.setObjectName("buttonGroup_4")
        self.buttonGroup_4.addButton(self.mgUButton)
        self.mgNButton = QtWidgets.QRadioButton(self.suspectTracker)
        self.mgNButton.setGeometry(QtCore.QRect(140, 80, 21, 20))
        self.mgNButton.setText("")
        self.mgNButton.setObjectName("mgNButton")
        self.buttonGroup_4.addButton(self.mgNButton)
        self.mgYButton = QtWidgets.QRadioButton(self.suspectTracker)
        self.mgYButton.setGeometry(QtCore.QRect(110, 80, 21, 20))
        self.mgYButton.setText("")
        self.mgYButton.setObjectName("mgYButton")
        self.buttonGroup_4.addButton(self.mgYButton)
        self.mpUButton = QtWidgets.QRadioButton(self.suspectTracker)
        self.mpUButton.setGeometry(QtCore.QRect(170, 100, 21, 20))
        self.mpUButton.setText("")
        self.mpUButton.setObjectName("mpUButton")
        self.buttonGroup_5 = QtWidgets.QButtonGroup(GameBoard)
        self.buttonGroup_5.setObjectName("buttonGroup_5")
        self.buttonGroup_5.addButton(self.mpUButton)
        self.mpYButton = QtWidgets.QRadioButton(self.suspectTracker)
        self.mpYButton.setGeometry(QtCore.QRect(110, 100, 21, 20))
        self.mpYButton.setText("")
        self.mpYButton.setObjectName("mpYButton")
        self.buttonGroup_5.addButton(self.mpYButton)
        self.mpNButton = QtWidgets.QRadioButton(self.suspectTracker)
        self.mpNButton.setGeometry(QtCore.QRect(140, 100, 21, 20))
        self.mpNButton.setText("")
        self.mpNButton.setObjectName("mpNButton")
        self.buttonGroup_5.addButton(self.mpNButton)
        self.ppUButton = QtWidgets.QRadioButton(self.suspectTracker)
        self.ppUButton.setGeometry(QtCore.QRect(170, 120, 21, 20))
        self.ppUButton.setText("")
        self.ppUButton.setObjectName("ppUButton")
        self.buttonGroup_6 = QtWidgets.QButtonGroup(GameBoard)
        self.buttonGroup_6.setObjectName("buttonGroup_6")
        self.buttonGroup_6.addButton(self.ppUButton)
        self.ppYButton = QtWidgets.QRadioButton(self.suspectTracker)
        self.ppYButton.setGeometry(QtCore.QRect(110, 120, 21, 20))
        self.ppYButton.setText("")
        self.ppYButton.setObjectName("ppYButton")
        self.buttonGroup_6.addButton(self.ppYButton)
        self.ppNButton = QtWidgets.QRadioButton(self.suspectTracker)
        self.ppNButton.setGeometry(QtCore.QRect(140, 120, 21, 20))
        self.ppNButton.setText("")
        self.ppNButton.setObjectName("ppNButton")
        self.buttonGroup_6.addButton(self.ppNButton)
        self.label_14 = QtWidgets.QLabel(self.suspectTracker)
        self.label_14.setGeometry(QtCore.QRect(100, 0, 91, 16))
        self.label_14.setObjectName("label_14")
        self.toolBox.addItem(self.suspectTracker, "")
	    # Weapon Tracker
        self.weaponTracker = QtWidgets.QWidget()
        self.weaponTracker.setGeometry(QtCore.QRect(0, 0, 201, 198))
        self.weaponTracker.setObjectName("weaponTracker")
        self.kYButton = QtWidgets.QRadioButton(self.weaponTracker)
        self.kYButton.setGeometry(QtCore.QRect(110, 40, 21, 20))
        self.kYButton.setText("")
        self.kYButton.setObjectName("kYButton")
        self.buttonGroup_8 = QtWidgets.QButtonGroup(GameBoard)
        self.buttonGroup_8.setObjectName("buttonGroup_8")
        self.buttonGroup_8.addButton(self.kYButton)
        self.gTrackerLabel = QtWidgets.QLabel(self.weaponTracker)
        self.gTrackerLabel.setGeometry(QtCore.QRect(0, 100, 101, 16))
        self.gTrackerLabel.setObjectName("gTrackerLabel")
        self.csYButton = QtWidgets.QRadioButton(self.weaponTracker)
        self.csYButton.setGeometry(QtCore.QRect(110, 20, 21, 20))
        self.csYButton.setText("")
        self.csYButton.setObjectName("csYButton")
        self.buttonGroup_7 = QtWidgets.QButtonGroup(GameBoard)
        self.buttonGroup_7.setObjectName("buttonGroup_7")
        self.buttonGroup_7.addButton(self.csYButton)
        self.lpUButton = QtWidgets.QRadioButton(self.weaponTracker)
        self.lpUButton.setGeometry(QtCore.QRect(170, 80, 21, 20))
        self.lpUButton.setText("")
        self.lpUButton.setObjectName("lpUButton")
        self.buttonGroup_10 = QtWidgets.QButtonGroup(GameBoard)
        self.buttonGroup_10.setObjectName("buttonGroup_10")
        self.buttonGroup_10.addButton(self.lpUButton)
        self.rYButton = QtWidgets.QRadioButton(self.weaponTracker)
        self.rYButton.setGeometry(QtCore.QRect(110, 60, 21, 20))
        self.rYButton.setText("")
        self.rYButton.setObjectName("rYButton")
        self.buttonGroup_9 = QtWidgets.QButtonGroup(GameBoard)
        self.buttonGroup_9.setObjectName("buttonGroup_9")
        self.buttonGroup_9.addButton(self.rYButton)
        self.wYButton = QtWidgets.QRadioButton(self.weaponTracker)
        self.wYButton.setGeometry(QtCore.QRect(110, 120, 21, 20))
        self.wYButton.setText("")
        self.wYButton.setObjectName("wYButton")
        self.buttonGroup_12 = QtWidgets.QButtonGroup(GameBoard)
        self.buttonGroup_12.setObjectName("buttonGroup_12")
        self.buttonGroup_12.addButton(self.wYButton)
        self.rTrackerLabel = QtWidgets.QLabel(self.weaponTracker)
        self.rTrackerLabel.setGeometry(QtCore.QRect(0, 60, 101, 16))
        self.rTrackerLabel.setObjectName("rTrackerLabel")
        self.gYButton = QtWidgets.QRadioButton(self.weaponTracker)
        self.gYButton.setGeometry(QtCore.QRect(110, 100, 21, 20))
        self.gYButton.setText("")
        self.gYButton.setObjectName("gYButton")
        self.buttonGroup_11 = QtWidgets.QButtonGroup(GameBoard)
        self.buttonGroup_11.setObjectName("buttonGroup_11")
        self.buttonGroup_11.addButton(self.gYButton)
        self.wNButton = QtWidgets.QRadioButton(self.weaponTracker)
        self.wNButton.setGeometry(QtCore.QRect(140, 120, 21, 20))
        self.wNButton.setText("")
        self.wNButton.setObjectName("wNButton")
        self.buttonGroup_12.addButton(self.wNButton)
        self.lpNButton = QtWidgets.QRadioButton(self.weaponTracker)
        self.lpNButton.setGeometry(QtCore.QRect(140, 80, 21, 20))
        self.lpNButton.setText("")
        self.lpNButton.setObjectName("lpNButton")
        self.buttonGroup_10.addButton(self.lpNButton)
        self.csUButton = QtWidgets.QRadioButton(self.weaponTracker)
        self.csUButton.setGeometry(QtCore.QRect(170, 20, 21, 20))
        self.csUButton.setText("")
        self.csUButton.setObjectName("csUButton")
        self.buttonGroup_7.addButton(self.csUButton)
        self.kNButton = QtWidgets.QRadioButton(self.weaponTracker)
        self.kNButton.setGeometry(QtCore.QRect(140, 40, 21, 20))
        self.kNButton.setText("")
        self.kNButton.setObjectName("kNButton")
        self.buttonGroup_8.addButton(self.kNButton)
        self.csTrackerLabel = QtWidgets.QLabel(self.weaponTracker)
        self.csTrackerLabel.setGeometry(QtCore.QRect(0, 20, 101, 16))
        self.csTrackerLabel.setObjectName("csTrackerLabel")
        self.lpYButton = QtWidgets.QRadioButton(self.weaponTracker)
        self.lpYButton.setGeometry(QtCore.QRect(110, 80, 21, 20))
        self.lpYButton.setText("")
        self.lpYButton.setObjectName("lpYButton")
        self.buttonGroup_10.addButton(self.lpYButton)
        self.kUButton = QtWidgets.QRadioButton(self.weaponTracker)
        self.kUButton.setGeometry(QtCore.QRect(170, 40, 21, 20))
        self.kUButton.setText("")
        self.kUButton.setObjectName("kUButton")
        self.buttonGroup_8.addButton(self.kUButton)
        self.csNButton = QtWidgets.QRadioButton(self.weaponTracker)
        self.csNButton.setGeometry(QtCore.QRect(140, 20, 21, 20))
        self.csNButton.setText("")
        self.csNButton.setObjectName("csNButton")
        self.buttonGroup_7.addButton(self.csNButton)
        self.wTrackerLabel = QtWidgets.QLabel(self.weaponTracker)
        self.wTrackerLabel.setGeometry(QtCore.QRect(0, 120, 101, 16))
        self.wTrackerLabel.setObjectName("wTrackerLabel")
        self.kTrackerLabel = QtWidgets.QLabel(self.weaponTracker)
        self.kTrackerLabel.setGeometry(QtCore.QRect(0, 40, 101, 16))
        self.kTrackerLabel.setObjectName("kTrackerLabel")
        self.gUButton = QtWidgets.QRadioButton(self.weaponTracker)
        self.gUButton.setGeometry(QtCore.QRect(170, 100, 21, 20))
        self.gUButton.setText("")
        self.gUButton.setObjectName("gUButton")
        self.buttonGroup_11.addButton(self.gUButton)
        self.rUButton = QtWidgets.QRadioButton(self.weaponTracker)
        self.rUButton.setGeometry(QtCore.QRect(170, 60, 21, 20))
        self.rUButton.setText("")
        self.rUButton.setObjectName("rUButton")
        self.buttonGroup_9.addButton(self.rUButton)
        self.rNButton = QtWidgets.QRadioButton(self.weaponTracker)
        self.rNButton.setGeometry(QtCore.QRect(140, 60, 21, 20))
        self.rNButton.setText("")
        self.rNButton.setObjectName("rNButton")
        self.buttonGroup_9.addButton(self.rNButton)
        self.label_15 = QtWidgets.QLabel(self.weaponTracker)
        self.label_15.setGeometry(QtCore.QRect(100, 0, 91, 16))
        self.label_15.setObjectName("label_15")
        self.gNButton = QtWidgets.QRadioButton(self.weaponTracker)
        self.gNButton.setGeometry(QtCore.QRect(140, 100, 21, 20))
        self.gNButton.setText("")
        self.gNButton.setObjectName("gNButton")
        self.buttonGroup_11.addButton(self.gNButton)
        self.wUButton = QtWidgets.QRadioButton(self.weaponTracker)
        self.wUButton.setGeometry(QtCore.QRect(170, 120, 21, 20))
        self.wUButton.setText("")
        self.wUButton.setObjectName("wUButton")
        self.buttonGroup_12.addButton(self.wUButton)
        self.lpTrackerLabel = QtWidgets.QLabel(self.weaponTracker)
        self.lpTrackerLabel.setGeometry(QtCore.QRect(0, 80, 101, 16))
        self.lpTrackerLabel.setObjectName("lpTrackerLabel")
        self.toolBox.addItem(self.weaponTracker, "")
        self.roomTracker = QtWidgets.QWidget()
        self.roomTracker.setGeometry(QtCore.QRect(0, 0, 201, 198))
        self.roomTracker.setObjectName("roomTracker")
        self.cmYButton_3 = QtWidgets.QRadioButton(self.roomTracker)
        self.cmYButton_3.setGeometry(QtCore.QRect(110, 40, 21, 20))
        self.cmYButton_3.setText("")
        self.cmYButton_3.setObjectName("cmYButton_3")
        self.buttonGroup_14 = QtWidgets.QButtonGroup(GameBoard)
        self.buttonGroup_14.setObjectName("buttonGroup_14")
        self.buttonGroup_14.addButton(self.cmYButton_3)
        self.mpTrackerLabel_3 = QtWidgets.QLabel(self.roomTracker)
        self.mpTrackerLabel_3.setGeometry(QtCore.QRect(0, 100, 101, 16))
        self.mpTrackerLabel_3.setObjectName("mpTrackerLabel_3")
        self.msYButton_3 = QtWidgets.QRadioButton(self.roomTracker)
        self.msYButton_3.setGeometry(QtCore.QRect(110, 20, 21, 20))
        self.msYButton_3.setText("")
        self.msYButton_3.setObjectName("msYButton_3")
        self.buttonGroup_13 = QtWidgets.QButtonGroup(GameBoard)
        self.buttonGroup_13.setObjectName("buttonGroup_13")
        self.buttonGroup_13.addButton(self.msYButton_3)
        self.mgUButton_3 = QtWidgets.QRadioButton(self.roomTracker)
        self.mgUButton_3.setGeometry(QtCore.QRect(170, 80, 21, 20))
        self.mgUButton_3.setText("")
        self.mgUButton_3.setObjectName("mgUButton_3")
        self.buttonGroup_16 = QtWidgets.QButtonGroup(GameBoard)
        self.buttonGroup_16.setObjectName("buttonGroup_16")
        self.buttonGroup_16.addButton(self.mgUButton_3)
        self.mwYButton_3 = QtWidgets.QRadioButton(self.roomTracker)
        self.mwYButton_3.setGeometry(QtCore.QRect(110, 60, 21, 20))
        self.mwYButton_3.setText("")
        self.mwYButton_3.setObjectName("mwYButton_3")
        self.buttonGroup_15 = QtWidgets.QButtonGroup(GameBoard)
        self.buttonGroup_15.setObjectName("buttonGroup_15")
        self.buttonGroup_15.addButton(self.mwYButton_3)
        self.ppYButton_3 = QtWidgets.QRadioButton(self.roomTracker)
        self.ppYButton_3.setGeometry(QtCore.QRect(110, 120, 21, 20))
        self.ppYButton_3.setText("")
        self.ppYButton_3.setObjectName("ppYButton_3")
        self.mwTrackerLabel_3 = QtWidgets.QLabel(self.roomTracker)
        self.mwTrackerLabel_3.setGeometry(QtCore.QRect(0, 60, 101, 16))
        self.mwTrackerLabel_3.setObjectName("mwTrackerLabel_3")
        self.mpYButton_3 = QtWidgets.QRadioButton(self.roomTracker)
        self.mpYButton_3.setGeometry(QtCore.QRect(110, 100, 21, 20))
        self.mpYButton_3.setText("")
        self.mpYButton_3.setObjectName("mpYButton_3")
        self.ppNButton_3 = QtWidgets.QRadioButton(self.roomTracker)
        self.ppNButton_3.setGeometry(QtCore.QRect(140, 120, 21, 20))
        self.ppNButton_3.setText("")
        self.ppNButton_3.setObjectName("ppNButton_3")
        self.mgNButton_3 = QtWidgets.QRadioButton(self.roomTracker)
        self.mgNButton_3.setGeometry(QtCore.QRect(140, 80, 21, 20))
        self.mgNButton_3.setText("")
        self.mgNButton_3.setObjectName("mgNButton_3")
        self.buttonGroup_16.addButton(self.mgNButton_3)
        self.msUButton_3 = QtWidgets.QRadioButton(self.roomTracker)
        self.msUButton_3.setGeometry(QtCore.QRect(170, 20, 21, 20))
        self.msUButton_3.setText("")
        self.msUButton_3.setObjectName("msUButton_3")
        self.buttonGroup_13.addButton(self.msUButton_3)
        self.cmNButton_3 = QtWidgets.QRadioButton(self.roomTracker)
        self.cmNButton_3.setGeometry(QtCore.QRect(140, 40, 21, 20))
        self.cmNButton_3.setText("")
        self.cmNButton_3.setObjectName("cmNButton_3")
        self.buttonGroup_14.addButton(self.cmNButton_3)
	    # Room Tracker
        self.msTrackerLabel_3 = QtWidgets.QLabel(self.roomTracker)
        self.msTrackerLabel_3.setGeometry(QtCore.QRect(0, 20, 101, 16))
        self.msTrackerLabel_3.setObjectName("msTrackerLabel_3")
        self.mgYButton_3 = QtWidgets.QRadioButton(self.roomTracker)
        self.mgYButton_3.setGeometry(QtCore.QRect(110, 80, 21, 20))
        self.mgYButton_3.setText("")
        self.mgYButton_3.setObjectName("mgYButton_3")
        self.buttonGroup_16.addButton(self.mgYButton_3)
        self.cmUButton_3 = QtWidgets.QRadioButton(self.roomTracker)
        self.cmUButton_3.setGeometry(QtCore.QRect(170, 40, 21, 20))
        self.cmUButton_3.setText("")
        self.cmUButton_3.setObjectName("cmUButton_3")
        self.buttonGroup_14.addButton(self.cmUButton_3)
        self.msNButton_3 = QtWidgets.QRadioButton(self.roomTracker)
        self.msNButton_3.setGeometry(QtCore.QRect(140, 20, 21, 20))
        self.msNButton_3.setText("")
        self.msNButton_3.setObjectName("msNButton_3")
        self.buttonGroup_13.addButton(self.msNButton_3)
        self.ppTrackerLabel_3 = QtWidgets.QLabel(self.roomTracker)
        self.ppTrackerLabel_3.setGeometry(QtCore.QRect(0, 120, 101, 16))
        self.ppTrackerLabel_3.setObjectName("ppTrackerLabel_3")
        self.cmTrackerLabel_3 = QtWidgets.QLabel(self.roomTracker)
        self.cmTrackerLabel_3.setGeometry(QtCore.QRect(0, 40, 101, 16))
        self.cmTrackerLabel_3.setObjectName("cmTrackerLabel_3")
        self.mpUButton_3 = QtWidgets.QRadioButton(self.roomTracker)
        self.mpUButton_3.setGeometry(QtCore.QRect(170, 100, 21, 20))
        self.mpUButton_3.setText("")
        self.mpUButton_3.setObjectName("mpUButton_3")
        self.mwUButton_3 = QtWidgets.QRadioButton(self.roomTracker)
        self.mwUButton_3.setGeometry(QtCore.QRect(170, 60, 21, 20))
        self.mwUButton_3.setText("")
        self.mwUButton_3.setObjectName("mwUButton_3")
        self.buttonGroup_15.addButton(self.mwUButton_3)
        self.mwNButton_3 = QtWidgets.QRadioButton(self.roomTracker)
        self.mwNButton_3.setGeometry(QtCore.QRect(140, 60, 21, 20))
        self.mwNButton_3.setText("")
        self.mwNButton_3.setObjectName("mwNButton_3")
        self.buttonGroup_15.addButton(self.mwNButton_3)
        self.label_16 = QtWidgets.QLabel(self.roomTracker)
        self.label_16.setGeometry(QtCore.QRect(100, 0, 91, 16))
        self.label_16.setObjectName("label_16")
        self.mpNButton_3 = QtWidgets.QRadioButton(self.roomTracker)
        self.mpNButton_3.setGeometry(QtCore.QRect(140, 100, 21, 20))
        self.mpNButton_3.setText("")
        self.mpNButton_3.setObjectName("mpNButton_3")
        self.ppUButton_3 = QtWidgets.QRadioButton(self.roomTracker)
        self.ppUButton_3.setGeometry(QtCore.QRect(170, 120, 21, 20))
        self.ppUButton_3.setText("")
        self.ppUButton_3.setObjectName("ppUButton_3")
        self.mgTrackerLabel_3 = QtWidgets.QLabel(self.roomTracker)
        self.mgTrackerLabel_3.setGeometry(QtCore.QRect(0, 80, 101, 16))
        self.mgTrackerLabel_3.setObjectName("mgTrackerLabel_3")
        self.mgUButton_4 = QtWidgets.QRadioButton(self.roomTracker)
        self.mgUButton_4.setGeometry(QtCore.QRect(170, 140, 21, 20))
        self.mgUButton_4.setText("")
        self.mgUButton_4.setObjectName("mgUButton_4")
        self.mpUButton_4 = QtWidgets.QRadioButton(self.roomTracker)
        self.mpUButton_4.setGeometry(QtCore.QRect(170, 160, 21, 20))
        self.mpUButton_4.setText("")
        self.mpUButton_4.setObjectName("mpUButton_4")
        self.ppUButton_4 = QtWidgets.QRadioButton(self.roomTracker)
        self.ppUButton_4.setGeometry(QtCore.QRect(170, 180, 21, 20))
        self.ppUButton_4.setText("")
        self.ppUButton_4.setObjectName("ppUButton_4")
        self.ppTrackerLabel_4 = QtWidgets.QLabel(self.roomTracker)
        self.ppTrackerLabel_4.setGeometry(QtCore.QRect(0, 180, 101, 16))
        self.ppTrackerLabel_4.setObjectName("ppTrackerLabel_4")
        self.mpTrackerLabel_4 = QtWidgets.QLabel(self.roomTracker)
        self.mpTrackerLabel_4.setGeometry(QtCore.QRect(0, 160, 101, 16))
        self.mpTrackerLabel_4.setObjectName("mpTrackerLabel_4")
        self.mpNButton_4 = QtWidgets.QRadioButton(self.roomTracker)
        self.mpNButton_4.setGeometry(QtCore.QRect(140, 160, 21, 20))
        self.mpNButton_4.setText("")
        self.mpNButton_4.setObjectName("mpNButton_4")
        self.ppYButton_4 = QtWidgets.QRadioButton(self.roomTracker)
        self.ppYButton_4.setGeometry(QtCore.QRect(110, 180, 21, 20))
        self.ppYButton_4.setText("")
        self.ppYButton_4.setObjectName("ppYButton_4")
        self.mgYButton_4 = QtWidgets.QRadioButton(self.roomTracker)
        self.mgYButton_4.setGeometry(QtCore.QRect(110, 140, 21, 20))
        self.mgYButton_4.setText("")
        self.mgYButton_4.setObjectName("mgYButton_4")
        self.mgTrackerLabel_4 = QtWidgets.QLabel(self.roomTracker)
        self.mgTrackerLabel_4.setGeometry(QtCore.QRect(0, 140, 101, 16))
        self.mgTrackerLabel_4.setObjectName("mgTrackerLabel_4")
        self.mgNButton_4 = QtWidgets.QRadioButton(self.roomTracker)
        self.mgNButton_4.setGeometry(QtCore.QRect(140, 140, 21, 20))
        self.mgNButton_4.setText("")
        self.mgNButton_4.setObjectName("mgNButton_4")
        self.mpYButton_4 = QtWidgets.QRadioButton(self.roomTracker)
        self.mpYButton_4.setGeometry(QtCore.QRect(110, 160, 21, 20))
        self.mpYButton_4.setText("")
        self.mpYButton_4.setObjectName("mpYButton_4")
        self.ppNButton_4 = QtWidgets.QRadioButton(self.roomTracker)
        self.ppNButton_4.setGeometry(QtCore.QRect(140, 180, 21, 20))
        self.ppNButton_4.setText("")
        self.ppNButton_4.setObjectName("ppNButton_4")
        self.toolBox.addItem(self.roomTracker, "")
        self.clueTrackerLabel = QtWidgets.QLabel(self.gameBoard)
        self.clueTrackerLabel.setGeometry(QtCore.QRect(640, 140, 101, 16))
        self.clueTrackerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.clueTrackerLabel.setObjectName("clueTrackerLabel")
	    # Start Locations?
        self.label_24 = QtWidgets.QLabel(self.gameBoard)
        self.label_24.setGeometry(QtCore.QRect(190, 410, 41, 41))
        self.label_24.setText("")
        self.label_24.setPixmap(QtGui.QPixmap("greenStart.jpg"))
        self.label_24.setScaledContents(True)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.gameBoard)
        self.label_25.setGeometry(QtCore.QRect(440, 160, 51, 41))
        self.label_25.setText("")
        self.label_25.setPixmap(QtGui.QPixmap("mustardStart.jpg"))
        self.label_25.setScaledContents(True)
        self.label_25.setObjectName("label_25")
        self.mwStart = QtWidgets.QLabel(self.gameBoard)
        self.mwStart.setGeometry(QtCore.QRect(330, 410, 41, 41))
        self.mwStart.setText("")
        self.mwStart.setPixmap(QtGui.QPixmap("whiteStart.jpg"))
        self.mwStart.setScaledContents(True)
        self.mwStart.setObjectName("mwStart")
        self.ppStart = QtWidgets.QLabel(self.gameBoard)
        self.ppStart.setGeometry(QtCore.QRect(70, 160, 51, 41))
        self.ppStart.setText("")
        self.ppStart.setPixmap(QtGui.QPixmap("plumStart.png"))
        self.ppStart.setScaledContents(True)
        self.ppStart.setObjectName("ppStart")
        self.mpStart = QtWidgets.QLabel(self.gameBoard)
        self.mpStart.setGeometry(QtCore.QRect(70, 300, 51, 41))
        self.mpStart.setText("")
        self.mpStart.setPixmap(QtGui.QPixmap("peacockStart.jpg"))
        self.mpStart.setScaledContents(True)
        self.mpStart.setObjectName("mpStart")
        self.msStart = QtWidgets.QLabel(self.gameBoard)
        self.msStart.setGeometry(QtCore.QRect(330, 50, 41, 41))
        self.msStart.setText("")
        self.msStart.setPixmap(QtGui.QPixmap("scarlettStart.jpg"))
        self.msStart.setScaledContents(True)
        self.msStart.setObjectName("msStart")
	    # Study Push Button
        self.study = QtWidgets.QPushButton(self.gameBoard)
        self.study.setGeometry(QtCore.QRect(90, 60, 101, 101))
        self.study.setAutoFillBackground(True)
        self.study.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("study.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.study.setIcon(icon6)
        self.study.setIconSize(QtCore.QSize(110, 100))
        self.study.setCheckable(False)
        self.study.setFlat(True)
        self.study.setObjectName("study")
	    # Hall Push Button
        self.hall = QtWidgets.QPushButton(self.gameBoard)
        self.hall.setGeometry(QtCore.QRect(230, 60, 101, 101))
        self.hall.setAutoFillBackground(True)
        self.hall.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("hall.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.hall.setIcon(icon7)
        self.hall.setIconSize(QtCore.QSize(110, 100))
        self.hall.setCheckable(False)
        self.hall.setFlat(True)
        self.hall.setObjectName("hall")
	    # Hallway between Study and Hall Push Button
        self.hallwayStudyHall = QtWidgets.QPushButton(self.gameBoard)
        self.hallwayStudyHall.setGeometry(QtCore.QRect(190, 90, 41, 41))
        self.hallwayStudyHall.setAutoFillBackground(True)
        self.hallwayStudyHall.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("carpet_2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.hallwayStudyHall.setIcon(icon8)
        self.hallwayStudyHall.setIconSize(QtCore.QSize(60, 60))
        self.hallwayStudyHall.setCheckable(False)
        self.hallwayStudyHall.setFlat(True)
        self.hallwayStudyHall.setObjectName("hallwayStudyHall")
	    # Lounge Push Button
        self.lounge = QtWidgets.QPushButton(self.gameBoard)
        self.lounge.setGeometry(QtCore.QRect(370, 60, 101, 101))
        self.lounge.setAutoFillBackground(True)
        self.lounge.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("lounge.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.lounge.setIcon(icon9)
        self.lounge.setIconSize(QtCore.QSize(110, 100))
        self.lounge.setCheckable(False)
        self.lounge.setFlat(True)
        self.lounge.setObjectName("lounge")
        self.hallwayHallLounge = QtWidgets.QPushButton(self.gameBoard)
        self.hallwayHallLounge.setGeometry(QtCore.QRect(330, 90, 41, 41))
        self.hallwayHallLounge.setAutoFillBackground(True)
        self.hallwayHallLounge.setText("")
        self.hallwayHallLounge.setIcon(icon8)
        self.hallwayHallLounge.setIconSize(QtCore.QSize(60, 60))
        self.hallwayHallLounge.setCheckable(False)
        self.hallwayHallLounge.setFlat(True)
        self.hallwayHallLounge.setObjectName("hallwayHallLounge")
        self.library = QtWidgets.QPushButton(self.gameBoard)
        self.library.setGeometry(QtCore.QRect(90, 200, 101, 101))
        self.library.setAutoFillBackground(True)
        self.library.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("library.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.library.setIcon(icon10)
        self.library.setIconSize(QtCore.QSize(110, 100))
        self.library.setCheckable(False)
        self.library.setFlat(True)
        self.library.setObjectName("library")
        self.billiardRoom = QtWidgets.QPushButton(self.gameBoard)
        self.billiardRoom.setGeometry(QtCore.QRect(230, 200, 101, 101))
        self.billiardRoom.setAutoFillBackground(True)
        self.billiardRoom.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("billiardRoom.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.billiardRoom.setIcon(icon11)
        self.billiardRoom.setIconSize(QtCore.QSize(110, 100))
        self.billiardRoom.setCheckable(False)
        self.billiardRoom.setFlat(True)
        self.billiardRoom.setObjectName("billiardRoom")
        self.diningRoom = QtWidgets.QPushButton(self.gameBoard)
        self.diningRoom.setGeometry(QtCore.QRect(370, 200, 101, 101))
        self.diningRoom.setAutoFillBackground(True)
        self.diningRoom.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("diningRoom.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.diningRoom.setIcon(icon12)
        self.diningRoom.setIconSize(QtCore.QSize(110, 100))
        self.diningRoom.setCheckable(False)
        self.diningRoom.setFlat(True)
        self.diningRoom.setObjectName("diningRoom")
        self.conservatory = QtWidgets.QPushButton(self.gameBoard)
        self.conservatory.setGeometry(QtCore.QRect(90, 340, 101, 101))
        self.conservatory.setAutoFillBackground(True)
        self.conservatory.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("conservatory.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.conservatory.setIcon(icon13)
        self.conservatory.setIconSize(QtCore.QSize(110, 100))
        self.conservatory.setCheckable(False)
        self.conservatory.setFlat(True)
        self.conservatory.setObjectName("conservatory")
        self.ballroom = QtWidgets.QPushButton(self.gameBoard)
        self.ballroom.setGeometry(QtCore.QRect(230, 340, 101, 101))
        self.ballroom.setAutoFillBackground(True)
        self.ballroom.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("ballroom.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ballroom.setIcon(icon14)
        self.ballroom.setIconSize(QtCore.QSize(110, 100))
        self.ballroom.setCheckable(False)
        self.ballroom.setFlat(True)
        self.ballroom.setObjectName("ballroom")
        self.kitchen = QtWidgets.QPushButton(self.gameBoard)
        self.kitchen.setGeometry(QtCore.QRect(370, 340, 101, 101))
        self.kitchen.setAutoFillBackground(True)
        self.kitchen.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("kitchen.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.kitchen.setIcon(icon15)
        self.kitchen.setIconSize(QtCore.QSize(110, 100))
        self.kitchen.setCheckable(False)
        self.kitchen.setFlat(True)
        self.kitchen.setObjectName("kitchen")
        self.hallwayStudyLibrary = QtWidgets.QPushButton(self.gameBoard)
        self.hallwayStudyLibrary.setGeometry(QtCore.QRect(120, 160, 41, 41))
        self.hallwayStudyLibrary.setAutoFillBackground(True)
        self.hallwayStudyLibrary.setText("")
        self.hallwayStudyLibrary.setIcon(icon8)
        self.hallwayStudyLibrary.setIconSize(QtCore.QSize(60, 60))
        self.hallwayStudyLibrary.setCheckable(False)
        self.hallwayStudyLibrary.setFlat(True)
        self.hallwayStudyLibrary.setObjectName("hallwayStudyLibrary")
        self.hallwayHallBilliardRoom = QtWidgets.QPushButton(self.gameBoard)
        self.hallwayHallBilliardRoom.setGeometry(QtCore.QRect(260, 160, 41, 41))
        self.hallwayHallBilliardRoom.setAutoFillBackground(True)
        self.hallwayHallBilliardRoom.setText("")
        self.hallwayHallBilliardRoom.setIcon(icon8)
        self.hallwayHallBilliardRoom.setIconSize(QtCore.QSize(60, 60))
        self.hallwayHallBilliardRoom.setCheckable(False)
        self.hallwayHallBilliardRoom.setFlat(True)
        self.hallwayHallBilliardRoom.setObjectName("hallwayHallBilliardRoom")
        self.hallwayLoungeDiningRoom = QtWidgets.QPushButton(self.gameBoard)
        self.hallwayLoungeDiningRoom.setGeometry(QtCore.QRect(400, 160, 41, 41))
        self.hallwayLoungeDiningRoom.setAutoFillBackground(True)
        self.hallwayLoungeDiningRoom.setText("")
        self.hallwayLoungeDiningRoom.setIcon(icon8)
        self.hallwayLoungeDiningRoom.setIconSize(QtCore.QSize(60, 60))
        self.hallwayLoungeDiningRoom.setCheckable(False)
        self.hallwayLoungeDiningRoom.setFlat(True)
        self.hallwayLoungeDiningRoom.setObjectName("hallwayLoungeDiningRoom")
        self.hallwayLibraryConservatory = QtWidgets.QPushButton(self.gameBoard)
        self.hallwayLibraryConservatory.setGeometry(QtCore.QRect(120, 300, 41, 41))
        self.hallwayLibraryConservatory.setAutoFillBackground(True)
        self.hallwayLibraryConservatory.setText("")
        self.hallwayLibraryConservatory.setIcon(icon8)
        self.hallwayLibraryConservatory.setIconSize(QtCore.QSize(60, 60))
        self.hallwayLibraryConservatory.setFlat(True)
        self.hallwayLibraryConservatory.setObjectName("hallwayLibraryConservatory")
        self.hallwayBilliardRoomBallroom = QtWidgets.QPushButton(self.gameBoard)
        self.hallwayBilliardRoomBallroom.setGeometry(QtCore.QRect(260, 300, 41, 41))
        self.hallwayBilliardRoomBallroom.setAutoFillBackground(True)
        self.hallwayBilliardRoomBallroom.setText("")
        self.hallwayBilliardRoomBallroom.setIcon(icon8)
        self.hallwayBilliardRoomBallroom.setIconSize(QtCore.QSize(60, 60))
        self.hallwayBilliardRoomBallroom.setFlat(True)
        self.hallwayBilliardRoomBallroom.setObjectName("hallwayBilliardRoomBallroom")
        self.hallwayDiningRoomKitchen = QtWidgets.QPushButton(self.gameBoard)
        self.hallwayDiningRoomKitchen.setGeometry(QtCore.QRect(400, 300, 41, 41))
        self.hallwayDiningRoomKitchen.setAutoFillBackground(True)
        self.hallwayDiningRoomKitchen.setText("")
        self.hallwayDiningRoomKitchen.setIcon(icon8)
        self.hallwayDiningRoomKitchen.setIconSize(QtCore.QSize(60, 60))
        self.hallwayDiningRoomKitchen.setFlat(True)
        self.hallwayDiningRoomKitchen.setObjectName("hallwayDiningRoomKitchen")
        self.hallwayLibraryBilliardRoom = QtWidgets.QPushButton(self.gameBoard)
        self.hallwayLibraryBilliardRoom.setGeometry(QtCore.QRect(190, 230, 41, 41))
        self.hallwayLibraryBilliardRoom.setAutoFillBackground(True)
        self.hallwayLibraryBilliardRoom.setText("")
        self.hallwayLibraryBilliardRoom.setIcon(icon8)
        self.hallwayLibraryBilliardRoom.setIconSize(QtCore.QSize(60, 60))
        self.hallwayLibraryBilliardRoom.setFlat(True)
        self.hallwayLibraryBilliardRoom.setObjectName("hallwayLibraryBilliardRoom")
        self.hallwayBilliardRoomDiningRoom = QtWidgets.QPushButton(self.gameBoard)
        self.hallwayBilliardRoomDiningRoom.setGeometry(QtCore.QRect(330, 230, 41, 41))
        self.hallwayBilliardRoomDiningRoom.setAutoFillBackground(True)
        self.hallwayBilliardRoomDiningRoom.setText("")
        self.hallwayBilliardRoomDiningRoom.setIcon(icon8)
        self.hallwayBilliardRoomDiningRoom.setIconSize(QtCore.QSize(60, 60))
        self.hallwayBilliardRoomDiningRoom.setFlat(True)
        self.hallwayBilliardRoomDiningRoom.setObjectName("hallwayBilliardRoomDiningRoom")
        self.hallwayConservatoryBallroom = QtWidgets.QPushButton(self.gameBoard)
        self.hallwayConservatoryBallroom.setGeometry(QtCore.QRect(190, 370, 41, 41))
        self.hallwayConservatoryBallroom.setAutoFillBackground(True)
        self.hallwayConservatoryBallroom.setText("")
        self.hallwayConservatoryBallroom.setIcon(icon8)
        self.hallwayConservatoryBallroom.setIconSize(QtCore.QSize(60, 60))
        self.hallwayConservatoryBallroom.setFlat(True)
        self.hallwayConservatoryBallroom.setObjectName("hallwayConservatoryBallroom")
        self.hallwayBallroomKitchen = QtWidgets.QPushButton(self.gameBoard)
        self.hallwayBallroomKitchen.setGeometry(QtCore.QRect(330, 370, 41, 41))
        self.hallwayBallroomKitchen.setAutoFillBackground(True)
        self.hallwayBallroomKitchen.setText("")
        self.hallwayBallroomKitchen.setIcon(icon8)
        self.hallwayBallroomKitchen.setIconSize(QtCore.QSize(60, 60))
        self.hallwayBallroomKitchen.setFlat(True)
        self.hallwayBallroomKitchen.setObjectName("hallwayBallroomKitchen")
        self.makeSuggestionButton = QtWidgets.QPushButton(self.gameBoard)
        self.makeSuggestionButton.setGeometry(QtCore.QRect(620, 470, 141, 41))
        self.makeSuggestionButton.setObjectName("makeSuggestionButton")
        self.leaveGameButton = QtWidgets.QPushButton(self.gameBoard)
        self.leaveGameButton.setGeometry(QtCore.QRect(620, 20, 141, 41))
        self.leaveGameButton.setObjectName("leaveGameButton")
        self.inGameOptionsButton = QtWidgets.QPushButton(self.gameBoard)
        self.inGameOptionsButton.setGeometry(QtCore.QRect(620, 80, 141, 41))
        self.inGameOptionsButton.setObjectName("inGameOptionsButton")
        self.makeAccusationButton = QtWidgets.QPushButton(self.gameBoard)
        self.makeAccusationButton.setGeometry(QtCore.QRect(620, 530, 141, 41))
        self.makeAccusationButton.setObjectName("makeAccusationButton")
        
	    # Clue Card Buttons
        self.pushButton = QtWidgets.QPushButton(self.gameBoard)
        self.pushButton.setGeometry(QtCore.QRect(80, 480, 61, 101))
        self.pushButton.setAutoFillBackground(True)
        self.pushButton.setIconSize(QtCore.QSize(110, 100))
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.gameBoard)
        self.pushButton_2.setGeometry(QtCore.QRect(160, 480, 61, 101))
        self.pushButton_2.setAutoFillBackground(True)
        self.pushButton_2.setIconSize(QtCore.QSize(110, 100))
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.gameBoard)
        self.pushButton_3.setGeometry(QtCore.QRect(240, 480, 61, 101))
        self.pushButton_3.setAutoFillBackground(True)
        self.pushButton_3.setIconSize(QtCore.QSize(110, 100))
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.gameBoard)
        self.pushButton_4.setGeometry(QtCore.QRect(320, 480, 61, 101))
        self.pushButton_4.setAutoFillBackground(True)
        self.pushButton_4.setIconSize(QtCore.QSize(110, 100))
        self.pushButton_4.setFlat(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.gameBoard)
        self.pushButton_5.setGeometry(QtCore.QRect(400, 480, 61, 101))
        self.pushButton_5.setAutoFillBackground(True)
        self.pushButton_5.setIconSize(QtCore.QSize(110, 100))
        self.pushButton_5.setFlat(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.gameBoard)
        self.pushButton_6.setGeometry(QtCore.QRect(480, 480, 61, 101))
        self.pushButton_6.setAutoFillBackground(True)
        self.pushButton_6.setIconSize(QtCore.QSize(110, 100))
        self.pushButton_6.setFlat(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.stackedWidget.addWidget(self.gameBoard)
        
        self.retranslateUi(GameBoard)
        self.stackedWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(GameBoard)

    def retranslateUi(self, GameBoard):
        _translate = QtCore.QCoreApplication.translate
        GameBoard.setWindowTitle(_translate("GameBoard", "Clue-Less"))
        
        self.playerOneLabel.setText(_translate("GameBoard", "Player 1:"))
        self.playerTwoLabel.setText(_translate("GameBoard", "Player 2:"))
        self.playerThreeLabel.setText(_translate("GameBoard", "Player 3:"))
        self.playerFourLabel.setText(_translate("GameBoard", "Player 4:"))
        self.playerFiveLabel.setText(_translate("GameBoard", "Player 5:"))
        self.playerSixLabel.setText(_translate("GameBoard", "Player 6:"))
        self.playerOneNameSlot.setText(_translate("GameBoard", "Waiting..."))
        self.playerTwoNameSlot.setText(_translate("GameBoard", "Waiting..."))
        self.playerThreeNameSlot.setText(_translate("GameBoard", "Waiting..."))
        self.playerFourNameSlot.setText(_translate("GameBoard", "Waiting..."))
        self.playerFiveNameSlot.setText(_translate("GameBoard", "Waiting..."))
        self.playerSixNameSlot.setText(_translate("GameBoard", "Waiting..."))
        self.startGameButton.setText(_translate("GameBoard", "Start Game"))
        self.cancelStartButton.setText(_translate("GameBoard", "Cancel"))

        self.continueButton.setText(_translate("GameBoard", "Continue"))
        self.characterSelectionLabel.setText(_translate("GameBoard", "Select Your Character"))

        self.msTrackerLabel.setText(_translate("GameBoard", "Miss Scarlett"))
        self.cmTrackerLabel.setText(_translate("GameBoard", "Colonel Mustard"))
        self.mwTrackerLabel.setText(_translate("GameBoard", "Mrs White"))
        self.mgTrackerLabel.setText(_translate("GameBoard", "Mr Green"))
        self.mpTrackerLabel.setText(_translate("GameBoard", "Mrs Peacock"))
        self.ppTrackerLabel.setText(_translate("GameBoard", "Professor Plum"))
        self.label_14.setText(_translate("GameBoard", "   Y      N      ?"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.suspectTracker), _translate("GameBoard", "Suspects"))
        self.gTrackerLabel.setText(_translate("GameBoard", "Revolver"))
        self.rTrackerLabel.setText(_translate("GameBoard", "Rope"))
        self.csTrackerLabel.setText(_translate("GameBoard", "Candlestick"))
        self.wTrackerLabel.setText(_translate("GameBoard", "Wrench"))
        self.kTrackerLabel.setText(_translate("GameBoard", "Knife"))
        self.label_15.setText(_translate("GameBoard", "   Y      N      ?"))
        self.lpTrackerLabel.setText(_translate("GameBoard", "Lead Pipe"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.weaponTracker), _translate("GameBoard", "Weapons"))
        self.mpTrackerLabel_3.setText(_translate("GameBoard", "Billiard Room"))
        self.mwTrackerLabel_3.setText(_translate("GameBoard", "Lounge"))
        self.msTrackerLabel_3.setText(_translate("GameBoard", "Study"))
        self.ppTrackerLabel_3.setText(_translate("GameBoard", "Dining Room"))
        self.cmTrackerLabel_3.setText(_translate("GameBoard", "Hall"))
        self.label_16.setText(_translate("GameBoard", "   Y      N      ?"))
        self.mgTrackerLabel_3.setText(_translate("GameBoard", "Library"))
        self.ppTrackerLabel_4.setText(_translate("GameBoard", "Professor Plum"))
        self.mpTrackerLabel_4.setText(_translate("GameBoard", "Mrs Peacock"))
        self.mgTrackerLabel_4.setText(_translate("GameBoard", "Conservatory"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.roomTracker), _translate("GameBoard", "Rooms"))
        self.clueTrackerLabel.setText(_translate("GameBoard", "Clue Tracker"))
        self.makeSuggestionButton.setText(_translate("GameBoard", "Make Suggestion"))
        self.leaveGameButton.setText(_translate("GameBoard", "Leave Game"))
        self.inGameOptionsButton.setText(_translate("GameBoard", "Options"))
        self.makeAccusationButton.setText(_translate("GameBoard", "Make Accusation"))
        self.pushButton.setText(_translate("GameBoard", "Card"))
        self.pushButton_2.setText(_translate("GameBoard", "Card"))
        self.pushButton_3.setText(_translate("GameBoard", "Card"))
        self.pushButton_4.setText(_translate("GameBoard", "Card"))
        self.pushButton_5.setText(_translate("GameBoard", "Card"))
        self.pushButton_6.setText(_translate("GameBoard", "Card"))